dist: trusty
sudo: required
language: c
compiler: gcc

env:
    - OVMF_ROOT="/usr/share/qemu"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-6
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
    - sudo apt-get install -qq gnu-efi
    - sudo apt-get install -qq qemu-system-x86 ovmf
    - sudo apt-get install -qq cmake
    - sudo apt-get install -qq mount dosfstools
    - sudo apt-get install -qq mtools parted gdisk
    - sudo apt-get install -qq python3-pip
    - sudo pip3 install pexpect
    # EDK2 dependencies
    #- sudo apt-get install -qq uuid-dev

script:
    - mkdir build-dir && cd build-dir
    - cmake ..
    - make
    - make uefi.img
